In [1]:
import pandas as pd, datetime as dt

In [2]:
import sys
sys.path.append('/Users/oisin-brogan/Code/step_suggestions/')
import rules
sys.path.append('/Users/oisin-brogan/Code/similar_images')
from read_exif import read_exif

In [3]:
%matplotlib inline

In [4]:
step_photos = pd.read_csv('/Users/oisin-brogan/Downloads/step_photos2/db.csv')

def read_exif_txt(txt_path):
    datetimes = {}
    with open(txt_path, 'r') as f:
        lines = f.readlines()
    for line in lines:
        if line.startswith('/'):
            key = line.split('//')[1][:-5] #getting just image id
            datetimes[key] = ""
        else:
            datetimes[key] = line.split('value ')[1].strip()
    return datetimes
    
def add_taken_at(db, txt_path):
    df = db.copy()
    dic = read_exif_txt(txt_path)
    series = pd.Series(dic)
    df = df.set_index('image_id')
    df.loc[:, 'taken_at'] = series
    df = df.reset_index()
    
    return df

step_photos = add_taken_at(step_photos, '/Users/oisin-brogan/Downloads/step_photos2/exif_data.txt')
step_photos.taken_at = step_photos.taken_at.map(rules.convert_exif_to_datetime)

Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on 2016:04:06 13:43:38+09:00
Failed on 2016:04:06 13:48:30+09:00
Failed on 2016:04:06 13:48:30+09:00
Failed on 2016:04:06 13:43:38+09:00
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on
Failed on

In [5]:
step_photos.head()

,image_id,id,provider_id,external_id,recipe_id,position,title,description,created_at,updated_at,deleted_at,ingredient_external_ids,taken_at
0,76a2d860a11e5153,3835651,1,NaN,718874,14,NaN,"Sprinkle with grated Cheddar if using, then ad...",2016-08-16T04:00:10,2016-10-05T12:45:10,NaN,NaN,2016-10-05 02:34:45
1,9f8fdb1b85f600ad,4381199,1,NaN,718874,1,NaN,Prep your vegetables,2016-10-04T17:59:43,2016-10-04T17:59:43,NaN,NaN,2016-10-03 15:35:48
2,177966cbaf3e3c52,3209490,1,NaN,718874,16,NaN,Pop the pie into the oven for about 55-60 minu...,2016-05-04T18:46:41,2016-10-05T12:45:10,NaN,NaN,2016-10-05 05:34:40
3,bab7fffff5af0b76,4381217,1,NaN,718874,11,NaN,"Finally, fold in the egg; this will add taste,...",2016-10-04T18:03:29,2016-10-05T12:45:10,NaN,NaN,2016-10-05 01:50:41
4,111e62439aec3e8b,4384201,1,NaN,718874,15,NaN,Decorate with a pattern that puts peaks in the...,2016-10-05T02:05:36,2016-10-05T12:45:10,NaN,NaN,2016-10-05 03:00:15

In [6]:
#Import classified image labels from csv

In [8]:
labels = pd.read_csv('/Users/oisin-brogan/Downloads/Classification/Model/3.1/step_photos2]\\.csv', names = ['image_id', 'label', 'confidence'])

In [9]:
labels.loc[:,'label'] = labels['label'].apply(lambda x: x[2:-3])

In [10]:
labels.head()

               image_id  label  confidence
0  0014a8196f1a86ca.jpg  other    0.876739
1  002688caa5c41fae.jpg   food    0.702269
2  0033188f95f411d5.jpg   food    0.992287
3  005df7e95340d42f.jpg  other    0.989434
4  0067133171d3d420.jpg   text    0.798736

In [78]:
label_counts = labels.label.value_counts()
label_counts

food      1794
text      1065
other      428
person      81
flower      67
Name: label, dtype: int64

In [79]:
label_counts.food/label_counts.sum()

0.52227074235807858

In [11]:
label_counts = labels.label.value_counts()
label_counts

food      2513
text       491
other      353
person      64
flower      14
Name: label, dtype: int64

In [12]:
label_counts.food/label_counts.sum()

0.73158660844250367

In [70]:
#food_image_ids = labels[labels.label == 'food'].image_id.apply(lambda x: x[:-4])
#step_photos[[i in food_image_ids.values for i in step_photos.image_id]].to_csv('/Users/oisin-brogan/Downloads/step_photos2/just_food_photos.csv')

In [12]:
label_counts.sum()

3435

In [13]:
#Let's look at a run of model on the photos (includes ones missed by foodet for now)

In [14]:
import ast

In [16]:
model_suggestions= pd.read_csv('/Users/oisin-brogan/Downloads/step_photos2/model_suggestions_without_no_taken_at.csv', names = ['recipe_id', 'suggestion_list'])
model_suggestions.suggestion_list = model_suggestions.suggestion_list.map(lambda x: ast.literal_eval(x))
model_suggestions = model_suggestions.set_index('recipe_id')
model_suggestions.head()

                                             suggestion_list
recipe_id
718874     [[[be591636e8b6d93d], [88dcd2c72e2993b6], [63b...
884338     [[[b2e7bed5c48b0865], [3762c242c84a242f], [927...
929291                                                    []
940244                                                    []
942667     [[[1355b85e692d6c1f, 27f3153ff4e8138f], [7093e...

In [17]:
model_results= pd.read_csv('/Users/oisin-brogan/Downloads/step_photos2/model_results_without_no_taken_at.csv', names = ['recipe_id', 'suggestion_list'])
model_results.suggestion_list = model_results.suggestion_list.map(lambda x: ast.literal_eval(x))
model_results = model_results.set_index('recipe_id')
model_results.head()

                          suggestion_list
recipe_id
718874                    [[True, False]]
884338     [[True, False], [True, False]]
929291                                 []
940244                                 []
942667                     [[True, True]]

In [18]:
recipe_finds = model_results.suggestion_list.map(lambda x: [li[0] and li[1] for li in x])

In [19]:
false_positives = recipe_finds.apply(lambda x: x if x else pd.np.NaN).dropna()[recipe_finds.apply(lambda x: sum(x) != len(x) if x else pd.np.NAN).dropna()]

In [37]:
sys.path.append('/Users/oisin-brogan/Code/step_suggestions/')
import rules

In [44]:
def overzealous_duplicates(recipe):
    test = rules.set_up_db_groups(recipe)
    test = rules.dup_removal_by_min_time(test, pd.Timedelta(seconds = 70))
    if test.empty:
        return False
    test = rules.dup_removal_by_hash_timed(test, 'recipe', 25, pd.Timedelta(minutes=150), 'phash')
    
    if test.shape[0] < 3:
        return True
    else:
        return False

In [55]:
def mistake_kind(recipe_id, suggestions):
    if recipe_id not in suggestions.index:
        return "No EXIF data available for any photo in recipe"
    else:
        recipe = step_photos[step_photos.recipe_id == r_id]
        relevant_suggestions = suggestions.loc[r_id, 'suggestion_list']
        
        if len(relevant_suggestions) == 1:
            if sum(model_results.loc[r_id, 'suggestion_list'][0]) == 2:
                return "Correct suggestion"
        
        #Check we have at least three photos
        if recipe.shape[0] < 3:
            return "Less than 3 photos"
        
        #Check we aren't missing more than 25% of taken_at data
        missing_taken_ats = sum(pd.isnull(recipe.taken_at))
        if float(missing_taken_ats)/recipe.shape[0] > .25:
            return 'Missing over 25% of EXIF data'
        
        #we can drop nans now
        recipe = recipe[~pd.isnull(recipe.taken_at)]
        
        #Check total time isn't over 2.5 hours
        total_recipe_time = max(recipe.taken_at) - min(recipe.taken_at)
        if total_recipe_time > pd.Timedelta(minutes = 150):
            return "Recipe over time limit of 2.5 hours"
        
        if overzealous_duplicates(recipe):
            return "Duplicate removal removed too many photos"
        
        return 'Photo too dissimilar'

In [56]:
sp_recipes = set(step_photos.recipe_id)

In [57]:
reasons = {}
for r_id in sp_recipes:
    reasons[r_id] = mistake_kind(r_id, model_suggestions)

/Users/oisin-brogan/Code/step_suggestions/rules.py:181: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  chronolical = db.sort('taken_at')
/Users/oisin-brogan/anaconda/lib/python3.6/site-packages/pandas/core/indexing.py:141: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
/Users/oisin-brogan/Code/step_suggestions/rules.py:151: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  chronolical = db.sort('taken_at').set_index('image_id').taken_at

In [58]:
pd.Series(reasons).value_counts().sort_values()

Missing over 25% of EXIF data                       5
Duplicate removal removed too many photos          30
Photo too dissimilar                               64
Recipe over time limit of 2.5 hours                91
No EXIF data available for any photo in recipe    151
Correct suggestion                                197
dtype: int64

In [32]:
197./(len(reasons)-5-151) #recall

0.5157068062827225

In [33]:
197/recipe_finds.apply(lambda x: len(x) if x else pd.np.NAN).sum() #precision

0.7323420074349443

In [35]:
#sum(pd.isnull(step_photos[step_photos.recipe_id == 718874].taken_at))

In [49]:
pd.Series(reasons)[pd.Series(reasons) == '?']

1174474    ?
1211790    ?
1225172    ?
1229967    ?
1251975    ?
1255473    ?
1256326    ?
1263081    ?
1264553    ?
1265993    ?
1275262    ?
1277221    ?
1277387    ?
1277475    ?
1277536    ?
1283598    ?
1285330    ?
1308668    ?
1316948    ?
1325058    ?
1325667    ?
1328762    ?
1332406    ?
1332443    ?
1336562    ?
1342849    ?
1343472    ?
1343530    ?
1345016    ?
1354849    ?
          ..
1368276    ?
1377467    ?
1382628    ?
1405977    ?
1449233    ?
1456201    ?
1462300    ?
1468669    ?
1474871    ?
1500982    ?
1507394    ?
1515854    ?
1516253    ?
1520443    ?
1524557    ?
1544309    ?
1549251    ?
1554478    ?
1556200    ?
1556283    ?
1560900    ?
1563165    ?
1563200    ?
1563257    ?
1565994    ?
1574911    ?
1618888    ?
1627814    ?
1636327    ?
1636487    ?
dtype: object

In [51]:
step_photos[step_photos.recipe_id == 1211790].sort_values(by = 'taken_at')

,image_id,id,provider_id,external_id,recipe_id,position,title,description,created_at,updated_at,deleted_at,ingredient_external_ids,taken_at
406,26540f2a7e07a10c,4444777,1,NaN,1211790,16,NaN,Slice the onions Best,2016-10-09T04:46:32,2016-10-09T04:49:06,NaN,NaN,2016-10-09 02:47:00
407,005df7e95340d42f,4444791,1,NaN,1211790,11,NaN,Slice the onions Best,2016-10-09T04:47:21,2016-10-09T04:49:06,NaN,NaN,2016-10-09 02:47:48
408,453b2c6ec541887a,4444801,1,NaN,1211790,6,NaN,Slice the onions Best,2016-10-09T04:48:24,2016-10-09T04:49:06,NaN,NaN,2016-10-09 02:48:56
409,b5ba042f61f2177e,4444808,1,NaN,1211790,1,NaN,Slice the onions Best,2016-10-09T04:49:05,2016-10-09T04:49:05,NaN,NaN,2016-10-09 02:49:37